services:
  postgres:
    image: postgres:16
    container_name: pg-turmas
    environment:
      POSTGRES_DB: turmasdb
      POSTGRES_USER: turmas
      POSTGRES_PASSWORD: turmas123
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - pgdata_turmas:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U turmas -d turmasdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata_turmas:
